deployment:
  tasks:
    - echo "📦 Installing dependencies..."
    - npm install
    - echo "🔧 Building Vite project..."
    - npm run build
    - echo "🧹 Cleaning old files in public_html..."
    - rm -rf ~/public_html/*
    - echo "🚀 Deploying dist/ to public_html/"
    - cp -R dist/* ~/public_html/
