---
deployment:
  tasks:
    - echo "📦 Устанавливаю зависимости..."
    - npm install
    - echo "🔧 Собираю проект..."
    - npm run build
    - echo "🚀 Копирую содержимое dist в public_html..."
    - rsync -a --delete dist/ ~/public_html/
